### ISSUE TITLE
Include of addJsFooterLibrary breaks when concatenating

### ISSUE THREAD

**Issue by m-strotmeier** [andstenberg-rs/t3-readspeaker-services#4]
Hi, 

in my recent project the include of `addJsFooterLibrary` breaks the whole website when JS is concatenated and compressed. I suggest to add JS by adding some more parameters (or even make it configurable), like:

**WebreaderbuttonViewHelper.php, Line 104:**
```
->addJsFooterLibrary('wr-main-script', htmlentities($arguments["scriptUrl"]), 'text/javascript', false, false, '', true);
```

How do you think about that?

Best regards
Marco

**Comment by nilshollmer-rs** [comment]
Added this fix with the latest version! Thanks for your report Marco!
Best regards,
Nils
