### ISSUE TITLE
Controller filename not PSR-4 conform

### ISSUE THREAD

**Issue by Hawkeye1909** [andstenberg-rs/t3-readspeaker-services#5]
It took me a while to figure that out: The controller filename is incorrect considering PSR-4. The class is called "**Readspeaker**ServicesController" so the filename should be "**Readspeaker**ServicesController.php" (lowercase s) but it is "**ReadSpeaker**ServicesController.php" (uppercase S). A small but significant difference.

**Comment by nilshollmer-rs** [comment]
Thank you for noticing this. I've created a pull request to fix this issue.
